Easy = [["4 + 12 = ?", 16],
        ["45 -34 = ?",  11],
        ["27 + 12 -18 = ?", 21],
        ['25 - 5 * 4 = ?', 5],
        ["18 + 45 / 5 - 3 * 2 = ?", 21],
        ["5! = ?", 120],
        ["3! + 2! = ?", 8],
        ["7 + 5! / 4! - 6 / 3 = ?", 10],
        ["(25 + 5) / 6 * 4  = ?", 20],
        ["4(3+c)+c=c+4; c=?", -2],
        ["​√​121 = ?" ,11],
        ["x = √​81 - √​64; x= ?", 1],
        ["x + y = 20;  x - y = 4; y = ?", 8]]

Normal = [["8(10−k)=2k; k = ?", 8],
          ["−4n−8=4(−3n+2); n=?",  2],
          ["4(3+c)+c=c+4; c=?", -2],
          ["​√​121 = ?" ,11],
          ["x = √​81 - √​64; x= ?", 1],
          ["y = √​16 * √​4 / √​9; y=?", 2],
          ["y−3=2(x+1); x= -2, y=?", 1],
          [" y*y = 4x/5 − 11; y= 5, x = ?", 45],
          ["How many unique ways are there to arrange the letters in the word CANNON?", 120],
          ["How many numbers between 1 and 100(inclusive) are divisible by 10 or 7", 23],
          ["y=−4x+6; ​3x+4y=-2 ; x=?", 2],
          ["−x+4y=−9; ​y=−2x-9; y=?", -3]]

Hard = [["Emily is packing her bags for her vacation. She has 6 unique Fabergé eggs, but only 3 fit in her bag. How many different groups of 3 Fabergé eggs can she take?", 20],
        ["You just got a free ticket for a boat ride, and you can bring along 2 friends! Unfortunately, you have 5 friends who want to come along. How many different groups of friends could you take with you?",  10],
        ["Omar is packing his bags for his vacation. He has 999 unique shirts, but only 5 fit in his bag. How many different groups of 5 shirts can he take?", 126],
        ["How many numbers between 1 and 100(inclusive) are divisible by 3 or 2?" ,67],
        ["You need to put your reindeer, Gloopin, Quentin, Ezekiel, and Lancer, in a single-file line to pull your sleigh. However, Quentin and Gloopin are best friends, so you have to put them next to each other, or they won't fly. How many ways can you arrange your reindeer?", 12],
        ["You need to put your reindeer, Gloopin, Balthazar, Bloopin, Prancer, and Quentin, in a single-file line to pull your sleigh. However, Prancer and Balthazar are best friends, so you have to put them next to each other, or they won't fly. How many ways can you arrange your reindeer?", 2],
        ["y−3=2(x+1); x= -2, y=?", 48],
        ["How many unique ways are there to arrange the letters in the word CANNON?", 120],
        ["How many numbers between 1 and 100(inclusive) are divisible by 10 or 7", 23],
        ["−x+4y=−9; ​y=−2x-9; y=?", -3],
        ["x = √​81 - √​64; x= ?", 1],
        ["y = √​16 * √​4 / √​9; y=?", 2],
        ["y−3=2(x+1); x= -2, y=?", 1],
        [" y*y = 4x/5 − 11; y= 5, x = ?", 45],
        ["y=−4x+6; ​3x+4y=-2 ; x=?", 2],
        ["−x+4y=−9; ​y=−2x-9; y=?", -3]]
